# Generated by Django 5.2.6 on 2025-11-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDetails',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_id', models.CharField(max_length=255, unique=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('company_phone', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('domain', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField()),
                ('added_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company__details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CompanyTypes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('added_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'company__types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemCategories',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('added_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item__categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemForms',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('form_name', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('added_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item__forms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemManufacturers',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('manufacturer_name', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('added_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item__manufacturers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemUnits',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('unit_name', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('added_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'item__units',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionGroupes',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tran_groupe_name', models.CharField(max_length=255)),
                ('tran_method', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('added_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transaction__groupes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionHeads',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tran_head_name', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('cp', models.FloatField()),
                ('mrp', models.FloatField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('editable', models.IntegerField()),
                ('status', models.IntegerField()),
                ('added_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transaction__heads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionMainHeads',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=255)),
                ('status', models.IntegerField()),
                ('added_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'transaction__main__heads',
                'managed': False,
            },
        ),
    ]
