from django.contrib.auth.backends import BaseBackend
from core.models import UserInfos  # auto-generated by inspectdb
from django.contrib.auth.models import User


class UserInfosBackend(BaseBackend):
    def authenticate(self, request, user_id=None, password=None):
        try:
            user = UserInfos.objects.get(id=user_id, password=password, status=1)
            # Create Django shadow user if not exists
            django_user, created = User.objects.get_or_create(username=user.id)
            return django_user
        except UserInfos.DoesNotExist:
            return None

    def get_user(self, user_id):
        try:
            return User.objects.get(pk=user_id)
        except User.DoesNotExist:
            return None
